# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5735c1c109af3b633ec7634b3fc0685379ee93056950778e4c913a2a8cdb3ce75fa81c827c5dda03112f8c032dcf9f9744b14e8146da8319142b601ebff5538d

test:
  secret_key_base: 8f3e8e6d99c6c1133305731e5eac99885db80cccdf40be055da7a19c0700fee0ba750d956fab017719b5c5ed8ebaf5cf057e9c828bec33c86cd62e8db35f1003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
